// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PagonationPatrick.Context;

namespace PagonationPatrick.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220210075346_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("PagonationPatrick.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "The Hitchhiker's Guide to the Galaxy"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ready Player One"
                        },
                        new
                        {
                            Id = 3,
                            Name = "1984"
                        },
                        new
                        {
                            Id = 4,
                            Name = "The Matrix Resurrections"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Diablo 2: Resurrected"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Super Nintendo Entertainment System"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Day of the Tentacle"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Back to the Future"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Toy Story"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Brave New World"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
